// Copyright 2024 splitkb.com (support@splitkb.com)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Myriad boilerplate
#define MYRIAD_ENABLE


//#define USE_I2C

#define TAPPING_TOGGLE 2
#define TAPPING_TERM 140

//#define OLED_ENABLE

// #define PIMORONI_TRACKBALL_ADDRESS 0x0A
#define POINTING_DEVICE_CS_PIN GP9
#define POINTING_DEVICE_RIGHT
#define CIRQUE_PINNACLE_SPI_MODE 1

#define SPI_USE_WAIT TRUE
//#define SPI_SELECT_MODE SPI_SELECT_MODE_PAD
#define POINTING_DEVICE_ROTATION_180
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#undef CIRQUE_PINNACLE_TAP_ENABLE
//#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X
#define POINTING_DEVICE_COMBINED
