AUTO_SHIFT_ENABLE = no
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
REPEAT_KEY_ENABLE=yes
#RGB_MATRIX_ENABLE=no
#RGBLIGHT_ENABLE = no
OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
DIGITIZER_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
